# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-27 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('idcargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecargo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('idconfiguracion', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('logo', models.TextField()),
            ],
            options={
                'db_table': 'configuracion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('idcontrato', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_adjudicacion', models.DateField(blank=True, null=True)),
                ('fecha_firma_contrato', models.DateField(blank=True, null=True)),
                ('monto_contrato', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('idempresa', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleSeguimiento',
            fields=[
                ('iddetalleseguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
                ('detalle', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'detalle_seguimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ejecucion',
            fields=[
                ('idejecucion', models.AutoField(primary_key=True, serialize=False)),
                ('plazo_ejecucion', models.IntegerField(blank=True, null=True)),
                ('orden_de_proceder', models.DateField(blank=True, null=True)),
                ('entrega_provisional', models.DateField(blank=True, null=True)),
                ('entrega_definitiva', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, max_length=250, null=True)),
                ('fecha_inicio_obra', models.DateField(blank=True, null=True)),
                ('fecha_conclusion_prog', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ejecucion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EjecucionFinanciera',
            fields=[
                ('id_detalle_ejecucion_financiera', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.DateField(blank=True, null=True)),
                ('certificado', models.CharField(blank=True, max_length=15, null=True)),
                ('avance_ejecutado', models.FloatField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'ejecucion_financiera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EjecucionFisica',
            fields=[
                ('id_detalle_ejecucion_fisica', models.AutoField(primary_key=True, serialize=False)),
                ('programado', models.FloatField(blank=True, null=True)),
                ('avace_actual', models.FloatField(blank=True, null=True)),
                ('ejecucion_fisica', models.FloatField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=250, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ejecucion_fisica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idempresa', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(blank=True, max_length=250, null=True)),
                ('nit', models.CharField(blank=True, max_length=25, null=True)),
                ('representante_legal', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Financiamiento',
            fields=[
                ('idfinanciamiento', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.FloatField(blank=True, null=True)),
                ('financiador', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'financiamiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Frentes',
            fields=[
                ('idfrentes', models.AutoField(primary_key=True, serialize=False)),
                ('frente', models.TextField(blank=True, max_length=250, null=True)),
                ('imgfrente', models.TextField(blank=True, max_length=250, null=True)),
                ('descripcion_condiciones', models.TextField(blank=True, null=True)),
                ('numerofrente', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'frentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('idgaleria', models.IntegerField(primary_key=True, serialize=False)),
                ('foto', models.TextField(blank=True, max_length=250, null=True)),
                ('tipo', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'galeria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('idgestion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=8, null=True)),
                ('observacion', models.CharField(blank=True, max_length=50, null=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
                ('estado', models.NullBooleanField()),
            ],
            options={
                'db_table': 'gestion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Localizacion',
            fields=[
                ('idlocalizacion', models.AutoField(primary_key=True, serialize=False)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('comunidad', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'localizacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('idlugar', models.AutoField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(blank=True, max_length=50, null=True)),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('municipio', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'lugar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('idoperacion', models.AutoField(primary_key=True, serialize=False)),
                ('ind_programado', models.CharField(blank=True, max_length=30, null=True)),
                ('ind_alcanzado', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'operacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ordendecambio',
            fields=[
                ('idordendecambio', models.AutoField(primary_key=True, serialize=False)),
                ('montoinicial', models.FloatField(blank=True, null=True)),
                ('montofinal', models.FloatField(blank=True, null=True)),
                ('fechainicial', models.DateField(blank=True, null=True)),
                ('fechafin', models.DateField(blank=True, null=True)),
                ('diasiniciales', models.IntegerField(blank=True, null=True)),
                ('diasadicionales', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('idusuario', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'ordendecambio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idpersona', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(blank=True, max_length=250, null=True)),
                ('apellido1', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('celular', models.CharField(blank=True, max_length=25, null=True)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('nombreprograma', models.CharField(blank=True, max_length=50, null=True)),
                ('codigosigma', models.IntegerField(blank=True, null=True)),
                ('idprograma', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'programa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proyectoactividad',
            fields=[
                ('idproyectoactividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproyectoactividad', models.CharField(blank=True, max_length=250, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=250, null=True)),
                ('codsisin', models.CharField(blank=True, max_length=15, null=True)),
                ('codsigma', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=5, null=True)),
                ('pvigente', models.FloatField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'proyectoactividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Responsables',
            fields=[
                ('idresponsable', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'responsables',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('idseguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'seguimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('idunidad', models.AutoField(primary_key=True, serialize=False)),
                ('secretaria', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.NullBooleanField()),
                ('fecha', models.DateField(blank=True, null=True)),
                ('codunidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'unidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('creacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
